apiVersion: v1
kind: Service
metadata:
  name: karsajobs-fe # Name of the service
  labels: # Labels for the service
    app: karsajobs-fe
    tier: frontend
spec: # Specification of the service
  type: NodePort # Type of service
  selector:
    app: karsajobs-fe # Selector to match pods
    tier: frontend # Tier label
  ports:
  - port: 8000
    nodePort: 30038 # Node port for external access