apiVersion: apps/v1
kind: StatefulSet # MongoDB StatefulSet
metadata:
  name: karsajobs-mongo # Name of the StatefulSet
  labels:
    app: karsajobs-mongo
    tier: database
spec: # Specification of the StatefulSet
  selector:
    matchLabels:
      app: karsajobs-mongo
      tier: database
  serviceName: karsajobs-mongo # Service name for MongoDB
  replicas: 1 # Number of replicas
  minReadySeconds: 10 # Minimum ready seconds for pods
  template: # Template for the pod
    metadata:
      labels:
        app: karsajobs-mongo
        tier: database 
    spec: # Pod specification
      terminationGracePeriodSeconds: 10 # Grace period for termination
      containers: # List of containers in the pod
      - name: mongo
        image: mongo:4.4
        env: # Environment variables for MongoDB
        - name: MONGO_INITDB_ROOT_USERNAME_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
        - name: MONGO_INITDB_ROOT_PASSWORD_FILE
          value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
        ports: # MongoDB port
        - containerPort: 27017
        volumeMounts: # Volume mounts for MongoDB
        - name: mongo-pv
          mountPath: /data/db
        - name: mongo-configmap
          mountPath: /config
        - name: mongo-secret
          mountPath: /etc/mongo-credentials
      volumes: # Volumes for MongoDB
        - name: mongo-pv # Persistent Volume for MongoDB
          persistentVolumeClaim:
            claimName: karsajobs-mongo-pvc # Persistent Volume Claim for MongoDB
        - name: mongo-configmap # ConfigMap for MongoDB
          configMap:
            name: karsajobs-mongo-config # ConfigMap name
            items: 
            - key: mongo.conf
              path: mongo.conf
        - name: mongo-secret # Secret for MongoDB credentials
          secret:
            secretName: karsajobs-mongo-secret
            items:
              - key: MONGO_ROOT_USERNAME
                path: MONGO_ROOT_USERNAME
              - key: MONGO_ROOT_PASSWORD
                path: MONGO_ROOT_PASSWORD