apiVersion: v1
kind: Service
metadata:
  name: karsajobs-mongo # Name of the MongoDB service
  labels:
    app: karsajobs-mongo # Application label
    tier: database # Database tier label
spec:
  clusterIP: None
  selector:
    app: karsajobs-mongo
    tier: backend
  ports: 
    - port: 27017 # MongoDB port
