apiVersion: v1
kind: PersistentVolume # Persistent Volume for MongoDB
metadata:
  name: karsajobs-mongo-pv # Name of the Persistent Volume
  labels:
    type: local # Label for the Persistent Volume
spec:
  storageClassName: manual # Storage class for the Persistent Volume
  capacity:
    storage: 1Gi # Storage capacity
  accessModes: # Access modes for the Persistent Volume
    - ReadWriteOnce
  hostPath: # Host path for the Persistent Volume
    path: /mnt/data/
---
apiVersion: v1
kind: PersistentVolumeClaim # Persistent Volume Claim for MongoDB
metadata:
  name: karsajobs-mongo-pvc # Name of the Persistent Volume Claim
spec:
  storageClassName: manual # Storage class for the Persistent Volume Claim
  accessModes: # Access modes for the Persistent Volume Claim
    - ReadWriteOnce
  resources: # Resource requests for the Persistent Volume Claim
    requests:
      storage: 1Gi