apiVersion: v1 # MongoDB ConfigMap
kind: ConfigMap # MongoDB configuration
metadata:
  name: karsajobs-mongo-config # Name of the ConfigMap
data:
  mongo.conf: | # MongoDB configuration file
    storage:
      dbPath: /data/db